management:
  server:
    port: 7979
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
      base-path: /

spring:
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true

info:
    project:
        version: #project.version#